CUDA_VISIBLE_DEVICES=6 nohup python train.py\
    --model_name gpt2\
    --experiment cnndm_bsz16\
    --task_prefixes ""\
    --train_path ../data/CnnDm/cnndm_train.txt\
    --dev_path ../data/CnnDm/cnndm_valid.txt\
    --max_len 1024\
    --number_of_gpu 1\
    --batch_size_per_gpu 8\
    --gradient_accumulation_steps 2\
    --effective_batch_size 16\
    --total_steps 30000\
    --print_every 200\
    --save_every 1000\
    --learning_rate 2e-5\
    --margin 0.5\
    --save_path_prefix ./simctg_cnndm_bsz16/ &> simctg_bsz16.out &